const ListMenu = () => {
  return [
    {
      name: "Dashboard",
      label: "Beranda",
      link: "/dashboard",
      type: "menu",
      svg: "beranda.svg",
      icon: false,
      active: true,
      child: [],
      roles: ["super admin", "admin web", "admin mobile", "bod"],
      header: false,
    },
    {
      name: "Komentar",
      label: "Komentar",
      link: "/komentar",
      type: "menu",
      icon: false,
      active: true,
    },
    {
      name: "AnalisaGlobal",
      label: "Analisa Global",
      link: "/analisa-global",
      type: "menu",
      icon: false,
      active: true,
    },
    {
      name: "PengeluaranCost",
      label: "Pengeluaran",
      link: "/pengeluaran",
      type: "menu",
      icon: false,
      active: true,
    },
    {
      name: "Pendapatan",
      label: "Pendapatan",
      link: "/pendapatan",
      type: "menu",
      icon: false,
      active: true,
    },
    {
      name: "FeedbackUser",
      label: "Feedback User",
      link: "/feedback-user",
      type: "menu",
      icon: false,
      active: true,
    },
    {
      name: "InfoEvent",
      label: "INFO & EVENT",
      link: "/info-event",
      type: "menu",
      icon: false,
      active: true,
    },
    {
      name: "Verification",
      label: "Verification",
      link: "/",
      type: "menu",
      icon: false,
      active: true,
    },
    {
      name: "VerificationIdCard",
      label: "Id Card",
      link: "/verification/id-card",
      type: "menu",
      icon: false,
      active: true,
    },
    {
      name: "VerificationProduct",
      label: "Product",
      link: "/verification/product",
      type: "menu",
      icon: false,
      active: true,
    },
    {
      name: "User",
      label: "User",
      link: "/users",
      type: "menu",
      icon: false,
      active: true,
    },
    {
      name: "CekVerifKTP",
      label: "Cek Verifikasi KTP",
      link: "/verifikasi-ktp",
      type: "menu",
      icon: false,
      active: true,
    },
    {
      name: "CekVerifBarang",
      label: "Cek Verifikasi Upload Barang Produk",
      link: "/verifikasi-barang",
      type: "menu",
      icon: false,
      active: true,
    },
    {
      name: "Voucher",
      label: "Voucher",
      link: "/voucher",
      type: "menu",
      icon: false,
      active: true,
    },
    {
      name: "Komplain",
      label: "Komplain",
      link: "/komplain",
      type: "menu",
      icon: false,
      active: true,
    },
    {
      name: "Bantuan",
      label: "Bantuan",
      link: "/bantuan",
      type: "menu",
      icon: false,
      active: true,
    },
    {
      name: "TentangAplikasi",
      label: "Tentang Aplikasi",
      link: "/tentang-aplikasi",
      type: "menu",
      icon: false,
      active: true,
    },
    {
      name: "Kategori",
      label: "Kategori",
      link: "/kategori",
      type: "menu",
      icon: false,
      active: true,
    },
    {
      name: "Dompet",
      label: "Dompet",
      link: "/dompet",
      type: "menu",
      icon: false,
      active: true,
    },
  ];
};

export default ListMenu;
